//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode
    {
        public Barcode()
        {
            this.Boxes = new HashSet<Box>();
        }
    
        public int Id { get; set; }
        public string CodeNumber { get; set; }
        public string CodeType { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Box> Boxes { get; set; }
    }
}
