//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public Box()
        {
            this.OrderLists = new HashSet<OrderList>();
        }
    
        public int Id { get; set; }
        public int BarcodeId { get; set; }
        public int ProductId { get; set; }
        public int PartCapOfBox { get; set; }
        public int PartQtyUnitID { get; set; }
        public int PartQtyLeft { get; set; }
        public int BoxUnitOfTotal { get; set; }
        public int BoxTotalOfTotal { get; set; }
        public string PONumber { get; set; }
        public int LocationID { get; set; }
        public int DeliveryId { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<OrderList> OrderLists { get; set; }
        public virtual Product Product { get; set; }
    }
}
