//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COG
    {
        public COG()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string UnitPrice { get; set; }
        public string PartQtyUnitID { get; set; }
        public string SetPrice { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
