//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryList
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public string BoxQuantiy { get; set; }
        public string PartCapOfBox { get; set; }
        public int DeliveryId { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
