//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulfilmentSKU
    {
        public FulfilmentSKU()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string SCName { get; set; }
        public string ASIN { get; set; }
        public Nullable<bool> IsDiscontinued { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
