//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLists = new HashSet<OrderList>();
        }
    
        public int Id { get; set; }
        public string OrderName { get; set; }
        public System.DateTime SoldDate { get; set; }
        public string SalesChannel { get; set; }
        public int OrderListId { get; set; }
        public string OrderAmount { get; set; }
    
        public virtual ICollection<OrderList> OrderLists { get; set; }
    }
}
