//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Boxes = new HashSet<Box>();
            this.ShipmentLists = new HashSet<ShipmentList>();
        }
    
        public int Id { get; set; }
        public string SKU { get; set; }
        public int FulfilmentSKUId { get; set; }
        public string Aliases { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<bool> IsDiscontinued { get; set; }
        public int CategoryId { get; set; }
        public int ColorId { get; set; }
        public int SizeId { get; set; }
        public int PartQtyUnitID { get; set; }
        public int COGSId { get; set; }
    
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual COG COG { get; set; }
        public virtual FulfilmentSKU FulfilmentSKU { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductSize ProductSize { get; set; }
        public virtual ICollection<ShipmentList> ShipmentLists { get; set; }
        public virtual QuantityUnit QuantityUnit { get; set; }
    }
}
