//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentList
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string BoxCapacity { get; set; }
        public string BoxQuantity { get; set; }
        public int ShipmentId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
